# Automatically generated by configure
# Configured with: './configure' '--platform=opendingux' '--sound-drivers=sdl'
CC = /opt/rs97-toolchain/bin/mipsel-linux-gcc
CXX = /opt/rs97-toolchain/bin/mipsel-linux-g++
AS = /opt/rs97-toolchain/bin/mipsel-linux-as
STRIP = /opt/rs97-toolchain/bin/mipsel-linux-strip
CFLAGS +=  -I/opt/rs97-toolchain/mipsel-buildroot-linux-musl/sysroot/usr/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT -Wno-unused-result
ASFLAGS += 
LDFLAGS += 
LDLIBS += -L/opt/rs97-toolchain/mipsel-buildroot-linux-musl/sysroot/usr/lib -lSDL -lpthread -lpng  -lm -lz

ARCH = mipsel
PLATFORM = opendingux
SOUND_DRIVERS = sdl
